### ISSUE TITLE
 TypeError: __call__() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by KehaoWu** [sinacloud/sae-python-dev-guide#133]
在本地运行saecloud后出现以下错误
    
    Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/sae_python_dev-1.3.3-py2.7.egg/EGG-INFO/scripts/dev_server.py", line 124, in _
            return app(environ, start_response)
          File "/usr/lib/python2.7/site-packages/sae_python_dev-1.3.3-py2.7.egg/sae/channel.py", line 90, in _
            return app(environ, start_response)
        TypeError: __call__() takes exactly 2 arguments (3 given)

index.wsgi代码：

     # encoding=utf-8
     import sys
     reload(sys)
     sys.setdefaultencoding("utf-8")
    import os,sys
    root = os.path.dirname(__file__)
    sys.path.insert(0, os.path.join(root, 'site-packages'))
    import time
    import os.path
    import tornado.httpserver
    import tornado.options
    import tornado.web
    import json
    from libs.config.getConfig import MysqlConfig
    import torndb
    from api import view
    
    application = tornado.web.Application(
         handlers=[
                  ],
        template_path=os.path.join(os.path.dirname(__file__), ""),
        static_path=os.path.join(os.path.dirname(__file__), "static"),
        debug=False
       )

**Comment by chanfung032** [comment]
tornado.web.application需要使用tornado worker才能运行，默认的worker只能运行wsgi应用。

详细请参见：http://www.sinacloud.com/doc/sae/python/tutorial.html#tornado

**Comment by KehaoWu** [comment]
谢谢，已解决
