### ISSUE TITLE
本地虚拟机调试如何设置为主机IP访问

### ISSUE THREAD

**Issue by KehaoWu** [sinacloud/sae-python-dev-guide#134]
>
[conda@localhost 1]$ dev_server.py --mysql=sae:sae@localhost:3306
MySQL: sae:sae@localhost:3306.app_sharemeurl
 * Running on http://localhost:8080/ (Press CTRL+C to quit)
 * Restarting with stat
MySQL: sae:sae@localhost:3306.app_sharemeurl

以上信息产生自虚拟机，如何在主机访问该站点，虚拟机IP:192.168.56.101

**Comment by chanfung032** [comment]
dev_server.py --host＝0.0.0.0

详细的参数可以参见：dev_server.py -h
