### ISSUE TITLE
你好，能不能在我的python项目中预装pandas？

### ISSUE THREAD

**Issue by cccbbbaaab** [sinacloud/sae-python-dev-guide#145]
我的应用地址是fdupharmacy.applinzi.com，能不能在其中预装pandas？

**Comment by nanshihui** [comment]
好像 很多库都没有。

**Comment by chanfung032** [comment]
你好，如果你有自己装c扩展的需求，建议使用容器python环境。详细见：https://www.sinacloud.com/doc/sae/docker/python-getting-started.html
